POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "React patterns",
    "author": "Michael Chan",
    "url": "https://reactpatterns.com/",
    "likes": 7,
    "userId": "609ee22978ed4e84306e5161"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Go To Statement Considered Harmful",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
    "likes": 123,
    "userId": "609ee22978ed4e84306e5161"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Canonical string reduction",
    "author": "Edsger W. Dijkstra",
    "url": "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
    "likes": 12,
    "userId": "609ee22d78ed4e84306e5162"
}